variables:
  MVN_CLI_OPTIONS: "--batch-mode --show-version"

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn ${MVN_CLI_OPTIONS} clean package -DskipTests
  allow_failure: false
  artifacts:
    when: on_success
    paths:
      - target/*.war
    expire_in: 30 days

test:
  stage: test
  script:
    - mvn {MVN_CLI_OPTIONS} test